export const UserActions = {
    GUEST_LOGIN_REQUEST: 'GUEST_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    GUEST_LOGIN_FAILURE: 'GUEST_LOGIN_FAILURE'


}


export const DashboardAction = {
    DASHBOARD_REQUEST: 'DASHBOARD_REQUEST',
    DASHBOARD_SUCCESS: 'DASHBOARD_SUCCESS',
    DASHBOARD_FAILURE: 'DASHBOARD_FAILURE'
}


export const addDashAction = {
    ADD_DASH_REQUEST: 'ADD_DASH_REQUEST',
    ADD_DASH_SUCCESS: 'ADD_DASH_SUCCESS',
    ADD_DASH_FAILURE: 'ADD_DASH_FAILURE'

}

export const CollectionAction = {
    COLLECTION_REQUEST: 'COLLECTION_REQUEST',
    COLLECTION_SUCCESS: 'COLLECTION_SUCCESS',
    COLLECTION_FAILURE: 'COLLECTION_FAILURE'
}

